apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/kubernetesz/springboot-demo:04c5fa70e2a72ab3e0e7a5173509c187935abdf5
          imagePullPolicy: Always
          name: springboot-demo
          ports:
            - containerPort: 8080
              protocol: TCP
