apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-demo
